service: serverless-example

provider:
  name: aws
  runtime: nodejs20.x
  region: eu-west-3
  stage: ${opt:stage, 'dev'}
  memorySize: 256
  timeout: 29  # Set below API Gateway's 30s limit to prevent timeout issues
  httpApi:
    cors: true
    payload: '2.0'
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - logs:CreateLogGroup
            - logs:CreateLogStream
            - logs:PutLogEvents
          Resource: '*'

functions:
  bookHandler:
    handler: dist/book/functions/http/book.handler
    events:
      - httpApi:
          path: /api/books
          method: '*'
      - httpApi:
          path: /api/books/{proxy+}
          method: '*'

  authorHandler:
    handler: dist/author/functions/http/author.handler
    events:
      - httpApi:
          path: /api/authors
          method: '*'
      - httpApi:
          path: /api/authors/{proxy+}
          method: '*'

  authorCreationCron:
    handler: dist/author/functions/cron/author-creation.handler
    events:
      - schedule:
          rate: rate(1 minute)
          enabled: true

  # To add a new HTTP handler:
  # 1. Create a new file: src/<module>/presentation/functions/http/<name>.http.ts
  # 2. tsup will automatically compile it to: dist/<module>/functions/http/<name>.cjs
  # 3. Add a new function here with the httpApi event pattern above

  # To add a new cron handler:
  # 1. Create a new file: src/<module>/presentation/functions/cron/<name>.cron.ts
  # 2. tsup will automatically compile it to: dist/<module>/functions/cron/<name>.cjs
  # 3. Add a new function here with the schedule event pattern above

plugins:
  - serverless-offline

custom:
  serverless-offline:
    httpPort: 3000
    noPrependStageInUrl: true
